# Generated by Django 3.0.8 on 2021-08-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noraSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('OPTION1', models.CharField(max_length=50)),
                ('OPTION2', models.CharField(max_length=50)),
                ('OPTION3', models.CharField(max_length=50)),
                ('OPTION4', models.CharField(max_length=50)),
            ],
        ),
    ]
