# Generated by Django 3.0.8 on 2021-08-22 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noraSys', '0002_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('NAME', models.CharField(max_length=50)),
                ('OPTION', models.IntegerField()),
                ('COMMENTS', models.CharField(max_length=150)),
            ],
        ),
    ]
